### ISSUE TITLE
请问可否添加指定端口和ip的功能,以及可否出一个只用来开启web服务器的biliup-http版本(也就是调用本地已经存在的biliup)

### ISSUE THREAD

**Issue by Weltolk** [limitcool/biliup-http#2]

**Comment by limitcool** [comment]
第一个功能是有意义的,可以添加此功能,第二个功能我没有听懂你的意思,现在上传就是用的biliup-rs,没必要用本地二进制的biliup-rs。

**Comment by Weltolk** [comment]
> 第一个功能是有意义的,可以添加此功能,第二个功能我没有听懂你的意思,现在上传就是用的biliup-rs,没必要用本地二进制的biliup-rs。

那么每次biliup-rs更新的话,biliup-http都会跟着更新吗= =

**Comment by limitcool** [comment]
> > 第一个功能是有意义的,可以添加此功能,第二个功能我没有听懂你的意思,现在上传就是用的biliup-rs,没必要用本地二进制的biliup-rs。
> 
> 那么每次biliup-rs更新的话,biliup-http都会跟着更新吗= =

会更新的,大部分更新,我只需要修改一下包依赖biliup-rs的版本号就可以了。

**Comment by limitcool** [comment]
已添加自定义端口功能.

**Comment by Weltolk** [comment]
> 已添加自定义端口功能.

谢谢

**Comment by limitcool** [comment]
可以点个star哈。
